# Generated by Django 3.1 on 2020-08-14 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254)),
                ('description', models.TextField()),
                ('author', models.CharField(max_length=254)),
                ('feature_image', models.ImageField(upload_to='blog/')),
                ('is_active', models.CharField(choices=[('T', 'Active'), ('F', 'In-Active')], max_length=1)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
    ]
